name: Run tests and lint
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.17.0"

      # Add caching
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install required deps
      - name: Install Dependencies
        run: npm install

      # Run tests and linter
      - name: Try to build
        run: npm run build
      - name: Run the tests
        run: npm run test
      - name: Run eslint 
        run: npm run lint
      - name: Run prettier
        run: npm run prettier-check
